version: '3.7'
services:
    minio:
      image: minio/minio:RELEASE.2021-06-14T01-29-23Z
      container_name: minio
      environment:
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=minio123
        - MINIO_ROOT_USER=minio
        - MINIO_ROOT_PASSWORD=minio123
      command: server --address 0.0.0.0:9000 /data
      ports:
        - "9000:9000"
      volumes:
        - ./minio-data:/data
      networks:
        network1:
          aliases:
            - minio

networks:
  network1: {}


      
